{
 "title": "UC04_Multichannel_Fraud1",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Filter_TransactionID",
    "label": "Transaction ID",
    "query": "SELECT ATM_Trx_ID, Mobile_Trx_ID, IBank_Trx_ID FROM uc04_data.results WHERE ATM_Trx_ID != \"\" AND Mobile_Trx_ID != \"\" AND IBank_Trx_ID != \"\""
   },
   {
    "name": "Filter_Receiver",
    "label": "Account Receiver",
    "query": "SELECT Account_Receiver FROM uc04_data.results"
   },
   {
    "name": "Filter_Sender",
    "label": "Account Sender",
    "query": "SELECT Account_Sender FROM uc04_data.results"
   }
  ]
 },
 "panels": [
  {
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT * FROM uc04_data.results LIMIT 50 ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 0 },
   "options": {
    "content": "<h3 style=\"font-weight: bold; font-family: sans-serif;\">Multi-channel Fraud Detection 1</h3>\n<hr style=\"height:2px;border-width:0;color:gray;background-color:gray\">\n<h4 style=\"font-weight: bold; font-family: sans-serif;\">Objectives:</h4>\n<h6 style=\"font-family: sans-serif; text-align: justify\">Deteksi transaksi transfer semua channel (ATM, MobileApp, IBank) dari beberapa account ke dalam satu account (BSI / Non BSI) yang sama dengan total nominal minimal ≥ 100jt rupiah dalam kurun waktu 1 jam\n</h6>"
   }
  },
  {
   "title": "Total Suspected Account",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT COUNT(DISTINCT(Account_Sender)) AS Total_Account_Sender FROM uc04_data.results",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Account Receiver",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT COUNT(DISTINCT(Account_Receiver)) AS Total_Account_Receiver FROM uc04_data.results",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Anomaly Transaction Frequency (Cumulative)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT COUNT(ATM_Trx_ID), COUNT(IBank_Trx_ID), COUNT(Mobile_Trx_ID) FROM uc04_data.results LIMIT 50 ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Transaction Amount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT SUM(ATM_Trx_Amount), SUM(Mobile_Trx_Amount), SUM(IBank_Trx_Amount) FROM uc04_data.results LIMIT 50 ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Suspected Account by Gender",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Gender, COUNT(Gender) FROM uc04_data.account_details WHERE Gender = \"Male\""
    }
   ]
  },
  {
   "title": "Top 3 Account Receiver (Suspected Account)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 14, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, ATM_Trx_Amount, Mobile_Trx_Amount, IBank_Trx_Amount FROM uc04_data.results LIMIT 3",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": " %ATM Transaction Amount ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT SUM(ATM_Trx_Amount), SUM(IBank_Trx_Amount), SUM(Mobile_Trx_Amount) FROM uc04_data.results LIMIT 50 ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT COUNT(Gender) FROM uc04_data.account_details WHERE Gender = \"Female\"",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "%Internet Banking Transaction Amount",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT SUM(ATM_Trx_Amount), SUM(IBank_Trx_Amount), SUM(Mobile_Trx_Amount) FROM uc04_data.results LIMIT 50 ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "All Detected Multichannel Transaction",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Anomaly_Datetime, Account_Receiver, Account_Sender, ATM_Trx_ID, Mobile_Trx_ID, IBank_Trx_ID, Total_Transaction FROM uc04_data.results WHERE Account_Receiver IN ($Filter_Receiver) AND Account_Sender IN ($Filter_Sender) \r\nAND (ATM_Trx_ID IN ($Filter_TransactionID) OR Mobile_Trx_ID IN ($Filter_TransactionID) OR IBank_Trx_ID IN ($Filter_TransactionID))",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "%Mobile Application Transaction Amount",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT SUM(Mobile_Trx_Amount), SUM(ATM_Trx_Amount), SUM(IBank_Trx_Amount) FROM uc04_data.results LIMIT 50 ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}