{
 "title": "UC04_Multichannel_Fraud1_Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Filter_Receiver",
    "label": "Account Receiver",
    "query": "SELECT Account_Receiver FROM uc04_data.results"
   },
   {
    "name": "Filter_Sender",
    "label": "Account Sender",
    "query": "SELECT Account_Sender FROM uc04_data.results"
   },
   {
    "name": "Filter_TransactionID",
    "label": "Transaction ID",
    "query": "SELECT ATM_Trx_ID, Mobile_Trx_ID, IBank_Trx_ID FROM uc04_data.results WHERE ATM_Trx_ID != \"\" AND Mobile_Trx_ID != \"\" AND IBank_Trx_ID != \"\""
   }
  ]
 },
 "panels": [
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 }, "format": "short", "valueName": "current" },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:left;margin-top:1em;margin-bottom:0.5em\"> Details</h1>\n<hr style=\"height:1px;background-color:#ffffff; text-align:right;\">"
   }
  },
  {
   "title": "Distribution of Transaction Amount by Channel",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 12, "x": 7, "y": 0 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, ATM_Trx_ID, Mobile_Trx_ID, IBank_Trx_ID, ATM_Trx_Amount, Mobile_Trx_Amount, IBank_Trx_Amount FROM uc04_data.results \r\nWHERE  Account_Receiver IN ($Filter_Receiver) AND Account_Sender IN ($Filter_Sender) \r\nAND (ATM_Trx_ID IN ($Filter_TransactionID) OR Mobile_Trx_ID IN ($Filter_TransactionID) OR IBank_Trx_ID IN ($Filter_TransactionID))",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Transaction Amount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, ATM_Trx_Amount, Mobile_Trx_Amount, IBank_Trx_Amount FROM uc04_data.results WHERE Account_Receiver IN ($Filter_Receiver)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Transaction Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, COUNT(DISTINCT(ATM_Trx_ID)), COUNT(DISTINCT(IBank_Trx_ID)), COUNT(DISTINCT(Mobile_Trx_ID)) FROM uc04_data.results WHERE Account_Receiver IN ($Filter_Receiver) ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Account Receiver Details",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 4 },
   "options": {
    "content": "<div style=\"text-align:center; font-family:sans-serif; display:table-cell; vertical-align:middle;\">\r\n  {{#if (eq Gender \"Female\")}}\r\n  <img src=\"https://raw.githubusercontent.com/tania21ciu/Web_Image/main/woman%20(1).png\"\r\n    width=\"180\" height=\"180\" style=\"border-radius:50%;\"></img>\r\n  {{/if}}\r\n  {{#if (eq Gender \"Male\")}}\r\n  <img src=\"https://raw.githubusercontent.com/tania21ciu/Web_Image/main/man%20(3).png\"\r\n    width=\"180\" height=\"180\" style=\"border-radius:50%;\"></img>\r\n  {{/if}}\r\n\r\n  <h2 style=\"margin:20px; color:white\">{{Full_Name}}</h2>\r\n  <h5 style=\"color:white\"> Born in {{Date_of_Birth}} |\r\n    <i class=\"fa fa-envelope\"><a style=\"font-family:sans-serif; color:white\"> {{Email_Address}}</p></i>\r\n  </h5>\r\n  <hr style=\"margin: 1rem; height:2px;border-width:0;color:gray;background-color:#caf0f8\">\r\n  <table style=\"margin:20px; border:none;\" width=\"93.5%\">\r\n    <tbody>\r\n      <tr>\r\n        <td\r\n          style=\"color:white; border:10px green; padding:8px 15px 8px 15px; text-align:center; border-radius: 50px; box-shadow: 3px 3px 3px #00b4d8;\">\r\n          <h6>Account ID<br>\r\n            <hr style=\"height:1px; background-color:white;\">{{Account_ID}}\r\n        </td>\r\n        <td\r\n          style=\"color:white; border:none; padding:8px 15px 8px 15px; text-align:center; border-radius: 50px; box-shadow: 3px 3px 3px #90e0ef;\">\r\n          <h6> Customer ID <br>\r\n            <hr style=\"height:1px; background-color:white;\">{{Customer_ID}}\r\n        </td>\r\n        <td\r\n          style=\"color:white; border:none; padding:8px 15px 8px 15px; text-align:center; border-radius: 50px; box-shadow: 3px 3px 3px #caf0f8;\">\r\n          <h6>KTP ID <br>\r\n            <hr style=\"height:1px; background-color:white;\">{{KTP_ID}}\r\n        </td>\r\n      </tr>\r\n    </tbody>\r\n  </table>\r\n</div>"
   },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT * FROM uc04_data.account_details WHERE Account_ID IN ($Filter_Receiver)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Sender Account",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, COUNT(DISTINCT(Account_Sender)) FROM uc04_data.results WHERE Account_Receiver IN ($Filter_Receiver)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Multi-Channel Transaction Conducted By Receiver",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 10 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Anomaly_Datetime, Account_Receiver, Account_Sender, ATM_Trx_ID, Mobile_Trx_ID, IBank_Trx_ID, Total_Transaction FROM uc04_data.results WHERE Account_Receiver IN ($Filter_Receiver)\r\nAND Account_Sender IN ($Filter_Sender) \r\nAND (ATM_Trx_ID IN ($Filter_TransactionID) OR Mobile_Trx_ID IN ($Filter_TransactionID) OR IBank_Trx_ID IN ($Filter_TransactionID))",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Detail Account Sender",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT DISTINCT(uc04_data.account_details.Account_ID), uc04_data.account_details.Customer_ID, uc04_data.account_details.KTP_ID, uc04_data.account_details.Full_Name, uc04_data.account_details.Date_of_Birth, uc04_data.account_details.Gender, uc04_data.account_details.Email_Address FROM uc04_data.account_details\r\nINNER JOIN uc04_data.results ON uc04_data.account_details.Account_ID=uc04_data.results.Account_Sender\r\nWHERE uc04_data.account_details.Account_ID IN ($Filter_Sender) AND uc04_data.results.Account_Receiver IN ($Filter_Receiver);",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 }, "format": "short", "valueName": "current" },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 9, "w": 3, "x": 0, "y": 25 }, "format": "short", "valueName": "current" },
  {
   "title": "Average ATM Transaction Amount over Time",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 8, "x": 3, "y": 25 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT ATM_Trx_Datetime, ATM_Trx_Amount FROM uc04_data.results WHERE ATM_Trx_Amount > 0 AND Account_Receiver IN ($Filter_Receiver)\r\nAND Account_Sender IN ($Filter_Sender) \r\nAND (ATM_Trx_ID IN ($Filter_TransactionID) OR Mobile_Trx_ID IN ($Filter_TransactionID) OR IBank_Trx_ID IN ($Filter_TransactionID))",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Details of ATM Transaction",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, Account_Sender, ATM_Trx_ID, ATM_Trx_Datetime, ATM_Trx_Amount FROM uc04_data.results WHERE ATM_Trx_Amount > 0 AND  Account_Receiver IN ($Filter_Receiver) \r\nAND Account_Sender IN ($Filter_Sender) \r\nAND (ATM_Trx_ID IN ($Filter_TransactionID) OR Mobile_Trx_ID IN ($Filter_TransactionID) OR IBank_Trx_ID IN ($Filter_TransactionID))\r\nGROUP BY  ATM_Trx_ID",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 }, "format": "short", "valueName": "current" },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 8, "w": 3, "x": 0, "y": 38 }, "format": "short", "valueName": "current" },
  {
   "title": "Average Mobile Banking Transaction Amount over Time",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 38 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Mobile_Trx_Datetime, Mobile_Trx_Amount FROM uc04_data.results WHERE Mobile_Trx_Amount > 0 AND Account_Receiver IN ($Filter_Receiver)\r\nAND Account_Sender IN ($Filter_Sender) \r\nAND (ATM_Trx_ID IN ($Filter_TransactionID) OR Mobile_Trx_ID IN ($Filter_TransactionID) OR IBank_Trx_ID IN ($Filter_TransactionID))",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Details of Mobile Application Transaction",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 38 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, Account_Sender, Mobile_Trx_ID, Mobile_Trx_Datetime, Mobile_Trx_Amount FROM uc04_data.results WHERE Mobile_Trx_Amount > 0 AND Account_Receiver IN ($Filter_Receiver) \r\nAND Account_Sender IN ($Filter_Sender) \r\nAND (ATM_Trx_ID IN ($Filter_TransactionID) OR Mobile_Trx_ID IN ($Filter_TransactionID) OR IBank_Trx_ID IN ($Filter_TransactionID))\r\nGROUP BY Mobile_Trx_ID",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 46 }, "format": "short", "valueName": "current" },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 9, "w": 3, "x": 0, "y": 49 }, "format": "short", "valueName": "current" },
  {
   "title": "Average Internet Transaction Amount over Time",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 49 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT IBank_Trx_Datetime, IBank_Trx_Amount FROM uc04_data.results WHERE IBank_Trx_Amount > 0 AND Account_Receiver IN ($Filter_Receiver) \r\nAND Account_Sender IN ($Filter_Sender) \r\nAND (ATM_Trx_ID IN ($Filter_TransactionID) OR Mobile_Trx_ID IN ($Filter_TransactionID) OR IBank_Trx_ID IN ($Filter_TransactionID))\r\n",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Details of Internet Banking Transaction",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 49 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, Account_Sender, IBank_Trx_ID, IBank_Trx_Datetime, IBank_Trx_Amount FROM uc04_data.results WHERE IBank_Trx_Amount > 0 AND  Account_Receiver IN ($Filter_Receiver) \r\nAND Account_Sender IN ($Filter_Sender) \r\nAND (ATM_Trx_ID IN ($Filter_TransactionID) OR Mobile_Trx_ID IN ($Filter_TransactionID) OR IBank_Trx_ID IN ($Filter_TransactionID))\r\nGROUP BY IBank_Trx_ID",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}