{
 "title": "Main dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "panels": [
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 }, "format": "short", "valueName": "current" },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 22, "x": 2, "y": 0 },
   "options": {
    "content": "<div style=\"margin-top:30px\">\n<h1 style=\"font-weight: bold; font-family: sans-serif; color: white\">Fraud Detection Dashboard</h3>\n<hr style=\"height:2px;border-width:0;color:gray;background-color:gray\">\n</div>"
   }
  },
  {
   "title": "Total Account Fraud",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "Grafana",
     "rawSql": "SELECT COUNT(DISTINCT(Account_Receiver))\r\nFROM Grafana.UC04_Results"
    },
    {
     "rawSql": "SELECT COUNT(DISTINCT(Grafana.UC9.Rekening_ID))\r\nFROM Grafana.UC9"
    },
    {
     "dataset": "Grafana",
     "rawSql": "SELECT COUNT(DISTINCT(Account_Credit_Card_ID)) FROM Grafana.UC6a"
    },
    {
     "dataset": "Grafana",
     "rawSql": "SELECT COUNT(DISTINCT(Account_Credit_Card_ID)) FROM Grafana.UC6b"
    }
   ]
  },
  {
   "title": "Total Suspected Account UC04",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT Account_Receiver) FROM Grafana.UC04_Results ;"
    }
   ]
  },
  {
   "title": "Total Suspected Account UC06a",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Grafana",
     "rawSql": "SELECT COUNT(DISTINCT(Account_Credit_Card_ID)) FROM Grafana.UC6a LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Suspected Account UC06b",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Grafana",
     "rawSql": "SELECT COUNT(DISTINCT(Account_Credit_Card_ID)) FROM Grafana.UC6b "
    }
   ]
  },
  {
   "title": "Total Suspected Account UC09",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT Rekening_ID) FROM Grafana.UC9 ;"
    }
   ]
  },
  {
   "title": "Total Transaction Amount (Rp)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "Grafana",
     "rawSql": "SELECT SUM(Total_Transaksi) FROM Grafana.UC9 LIMIT 50 "
    },
    {
     "dataset": "Grafana",
     "rawSql": "SELECT ATM_Trx_Amount, Mobile_Trx_Amount, IBank_Trx_Amount FROM Grafana.UC04_Results"
    },
    {
     "dataset": "Grafana",
     "rawSql": "SELECT SUM(Credit_Card_Trx_Amount) FROM Grafana.UC6a LIMIT 50 "
    },
    {
     "dataset": "Grafana",
     "rawSql": "SELECT SUM(Credit_Card_Trx_Amount) FROM Grafana.UC6b LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Suspected Account Use Case per Time",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(DISTINCT Account_Receiver) as \"Use Case 04\",\r\n    Anomaly_Datetime\r\nFROM Grafana.UC04_Results\r\nGROUP BY Anomaly_Datetime\r\n ;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    COUNT(DISTINCT Rekening_ID) as \"Use Case 09\",\r\n    Anomaly_timestamp\r\nFROM Grafana.UC9  \r\nGROUP BY Anomaly_timestamp\r\n ;\r\n"
    },
    {
     "dataset": "Grafana",
     "rawSql": "SELECT COUNT(DISTINCT Account_Credit_Card_ID) AS \"Use Case 06a\", Anomaly_timestamp FROM Grafana.UC6a\r\nGROUP BY Anomaly_timestamp;\r\n"
    },
    {
     "rawSql": "SELECT COUNT(DISTINCT Account_Credit_Card_ID) AS \"Use Case 06b\", Anomaly_timestamp FROM Grafana.UC6b\r\nGROUP BY Anomaly_timestamp;"
    }
   ]
  },
  {
   "title": "%Fraud Rate by Suspected Account Use Case",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(DISTINCT Account_Receiver) as UC04\r\nFROM Grafana.UC04_Results  \r\n ;"
    },
    {
     "rawSql": "SELECT \r\n    COUNT(DISTINCT Account_Credit_Card_ID) as UC06a\r\nFROM Grafana.UC6a ;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    COUNT(DISTINCT Account_Credit_Card_ID) as UC06b\r\nFROM Grafana.UC6b ;\r\n"
    },
    {
     "dataset": "TigerGraph",
     "rawSql": "SELECT \r\n    COUNT(DISTINCT Rekening_ID) as UC09\r\nFROM Grafana.UC9 ;\r\n"
    }
   ]
  },
  {
   "title": "Total Transaction UC04",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "Grafana",
     "rawSql": "SELECT Account_Receiver, ATM_Trx_Amount, Mobile_Trx_Amount, IBank_Trx_Amount\r\nFROM Grafana.UC04_Results "
    }
   ]
  },
  {
   "title": "Total Transaction UC06a",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Grafana",
     "rawSql": "SELECT SUM(Credit_Card_Trx_Amount) FROM Grafana.UC6a LIMIT 50 "
    }
   ]
  },
  {
   "title": "%Fraud Rate by Transaction Amount Use Case",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(Total_Transaction) as UC04\r\n \r\nFROM Grafana.UC04_Results \r\n\r\n ;"
    },
    {
     "rawSql": "SELECT \r\n    SUM(Total_Transaksi) as UC09\r\n\r\nFROM Grafana.UC9  \r\n\r\n ;"
    },
    {
     "rawSql": "SELECT \r\n    SUM(Credit_Card_Trx_Amount) as UC06a\r\n \r\nFROM Grafana.UC6a\r\n\r\n ;"
    },
    {
     "rawSql": "SELECT \r\n    SUM(Credit_Card_Trx_Amount) as UC06b\r\n \r\nFROM Grafana.UC6b\r\n\r\n ;"
    }
   ]
  },
  {
   "title": "Total Transaction Amount Use Case per Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(ATM_Trx_Amount + Mobile_Trx_Amount + IBank_Trx_Amount) AS \"Use Case 04\", \r\nAnomaly_Datetime\r\nFROM Grafana.UC04_Results \r\nGROUP BY Anomaly_Datetime"
    },
    {
     "rawSql": "SELECT \r\n    SUM(Total_Transaksi) as \"Use Case 09\",\r\n    Anomaly_timestamp\r\nFROM Grafana.UC9\r\nGROUP BY Anomaly_timestamp;\r\n"
    },
    {
     "rawSql": "SELECT SUM(Credit_Card_Trx_Amount) AS \"Use Case 06a\", Anomaly_timestamp FROM Grafana.UC6a \r\nWHERE Anomaly_timestamp IS NOT NULL\r\nGROUP BY Anomaly_timestamp"
    },
    {
     "rawSql": "SELECT Anomaly_timestamp, SUM(Credit_Card_Trx_Amount) AS \"Use Case 06b\" FROM Grafana.UC6b\r\nWHERE Anomaly_timestamp IS NOT NULL\r\nGROUP BY Anomaly_timestamp"
    }
   ]
  },
  {
   "title": "Total Transaction UC06b",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Grafana",
     "rawSql": "SELECT SUM(Credit_Card_Trx_Amount) FROM Grafana.UC6b LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Transaction UC09",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Grafana",
     "rawSql": "SELECT SUM(Total_Transaksi) FROM Grafana.UC9 LIMIT 50 "
    }
   ]
  }
 ]
}