{
 "title": "UC04_Multichannel_Fraud1_Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Filter_Receiver",
    "label": "Account Receiver",
    "query": "SELECT Account_Receiver FROM Grafana.UC04_Results"
   },
   {
    "name": "Filter_Sender",
    "label": "Account Sender",
    "query": "SELECT Account_Sender FROM Grafana.UC04_Results"
   },
   {
    "name": "Filter_TransactionID",
    "label": "Transaction ID",
    "query": "SELECT ATM_Trx_ID, Mobile_Trx_ID, IBank_Trx_ID FROM Grafana.UC04_Results WHERE ATM_Trx_ID != \"\" AND Mobile_Trx_ID != \"\" AND IBank_Trx_ID != \"\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"http://172.16.11.222:3000/d/2tQSaThVz/uc04_multichannel_fraud1?orgId=1&from=1673575290146&to=1673596890146\">\n<img src=\"https://raw.githubusercontent.com/tania21ciu/Web_Image/main/back.png\" style=\"width:60px;height:60px;\">\n</a>"
   }
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 4, "w": 2, "x": 1, "y": 0 }, "format": "short", "valueName": "current" },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 0 },
   "options": {
    "content": "<div style=\"margin-top:20px\">\n<h1 style=\"text-align:left;margin-bottom:0.5em;font-weight:bold; font-family:sans-serif; color:white\"> Details</h1>\n<hr style=\"height:2px;background-color:gray; text-align:right;\">\n</div>"
   }
  },
  {
   "title": "Distribution of Transaction Amount by Channel",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 12, "x": 7, "y": 3 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, ATM_Trx_ID, Mobile_Trx_ID, IBank_Trx_ID, ATM_Trx_Amount, Mobile_Trx_Amount, IBank_Trx_Amount FROM Grafana.UC04_Results\r\nWHERE  Account_Receiver IN ($Filter_Receiver) AND Account_Sender IN ($Filter_Sender)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Transaction Amount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, ATM_Trx_Amount, Mobile_Trx_Amount, IBank_Trx_Amount FROM Grafana.UC04_Results \r\nWHERE Account_Receiver IN ($Filter_Receiver)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Account Receiver Details",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 17, "w": 7, "x": 0, "y": 4 },
   "options": {
    "content": "<center>\r\n<div style=\"text-align:center; font-family:sans-serif; display:table-cell; vertical-align:middle; border: 3px solid white; padding-top: 50px; padding-bottom:50px; padding-left:30px; padding-right:30px; border-radius:20px\">\r\n  {{#if (eq Gender \"Female\")}}\r\n  <img src=\"https://raw.githubusercontent.com/tania21ciu/Web_Image/main/woman%20(1).png\"\r\n    width=\"180\" height=\"180\" style=\"border-radius:50%;\"></img>\r\n  {{/if}}\r\n  {{#if (eq Gender \"Male\")}}\r\n  <img src=\"https://raw.githubusercontent.com/tania21ciu/Web_Image/main/man%20(3).png\"\r\n    width=\"180\" height=\"180\" style=\"border-radius:50%;\"></img>\r\n  {{/if}}\r\n  {{#if (eq Gender \"No Data\")}}\r\n  <img src=\"https://raw.githubusercontent.com/tania21ciu/Web_Image/main/man.png\"\r\n    width=\"180\" height=\"180\" style=\"border-radius:50%;\"></img>\r\n  {{/if}}\r\n\r\n  <h2 style=\"margin:20px; color:white\">{{Full_Name}}</h2>\r\n  <h5 style=\"color:white\"> Born in {{Date_of_Birth}} |\r\n    <i class=\"fa fa-envelope\"><a style=\"font-family:sans-serif; color:white\"> {{Email_Address}}</p></i>\r\n  </h5>\r\n  <hr style=\"margin: 1rem; height:2px;border-width:0;color:gray;background-color:#caf0f8\">\r\n  <table style=\"margin:20px; border:none;\" width=\"93.5%\">\r\n    <tbody>\r\n      <tr>\r\n        <td\r\n          style=\"color:white; border:10px green; padding:8px 15px 8px 15px; text-align:center; border-radius: 50px; box-shadow: 3px 3px 3px #00b4d8;\">\r\n          <h6>Account ID<br>\r\n            <hr style=\"height:1px; background-color:white;\">{{Account_ID}}\r\n        </td>\r\n        <td\r\n          style=\"color:white; border:none; padding:8px 15px 8px 15px; text-align:center; border-radius: 50px; box-shadow: 3px 3px 3px #90e0ef;\">\r\n          <h6> Customer ID <br>\r\n            <hr style=\"height:1px; background-color:white;\">{{Customer_ID}}\r\n        </td>\r\n        <td\r\n          style=\"color:white; border:none; padding:8px 15px 8px 15px; text-align:center; border-radius: 50px; box-shadow: 3px 3px 3px #caf0f8;\">\r\n          <h6>KTP ID <br>\r\n            <hr style=\"height:1px; background-color:white;\">{{KTP_ID}}\r\n        </td>\r\n      </tr>\r\n    </tbody>\r\n  </table>\r\n</div>\r\n</center>"
   },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT * FROM Grafana.UC04_Account_Details WHERE Account_ID IN ($Filter_Receiver)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Transaction Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, COUNT(IBank_Trx_ID) FROM Grafana.UC04_Results \r\nWHERE Account_Receiver IN ($Filter_Receiver) AND IBank_Trx_ID != \"\" AND Account_Sender IN ($Filter_Sender)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "rawSql": "SELECT Account_Receiver, COUNT(ATM_Trx_ID) FROM Grafana.UC04_Results \r\nWHERE Account_Receiver IN ($Filter_Receiver) AND ATM_Trx_ID != \"\" AND Account_Sender IN ($Filter_Sender)"
    },
    {
     "rawSql": "SELECT Account_Receiver, COUNT(Mobile_Trx_ID) FROM Grafana.UC04_Results \r\nWHERE Account_Receiver IN ($Filter_Receiver) AND Mobile_Trx_ID != \"\" AND Account_Sender IN ($Filter_Sender)"
    }
   ]
  },
  {
   "title": "Total Sender Account",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, COUNT(DISTINCT(Account_Sender)) FROM Grafana.UC04_Results  \r\nWHERE Account_Receiver IN ($Filter_Receiver) AND Account_Sender IN ($Filter_Sender)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Multi-Channel Transaction Conducted By Receiver",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 13 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Anomaly_Datetime, Account_Receiver, Account_Sender, ATM_Trx_ID, ATM_Trx_Amount, Mobile_Trx_ID, Mobile_Trx_Amount, IBank_Trx_ID, IBank_Trx_Amount FROM Grafana.UC04_Results \r\nWHERE Account_Receiver IN ($Filter_Receiver) AND Account_Sender IN ($Filter_Sender)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Detail Account Sender",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT DISTINCT(Grafana.UC04_Account_Details.Account_ID), Grafana.UC04_Account_Details.Customer_ID, Grafana.UC04_Account_Details.KTP_ID, Grafana.UC04_Account_Details.Full_Name, Grafana.UC04_Account_Details.Date_of_Birth, Grafana.UC04_Account_Details.Gender, Grafana.UC04_Account_Details.Email_Address FROM Grafana.UC04_Account_Details\r\nINNER JOIN Grafana.UC04_Results ON Grafana.UC04_Account_Details.Account_ID=Grafana.UC04_Results.Account_Sender\r\nWHERE Grafana.UC04_Account_Details.Account_ID IN ($Filter_Sender) AND Grafana.UC04_Results.Account_Receiver IN ($Filter_Receiver);",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<div style=\"border: 3px solid #7CFFB2; text-align:center; border-radius:10px; margin-top:30px\">\n<h3 style=\"margin-top:10px; font-family:sans-serif; color:white; font-weight:bold\">ATM Channel</h1>\n</div>"
   }
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 9, "w": 3, "x": 0, "y": 29 }, "format": "short", "valueName": "current" },
  {
   "title": "Average ATM Transaction Amount over Time",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 8, "x": 3, "y": 29 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT ATM_Trx_Datetime, ATM_Trx_Amount FROM Grafana.UC04_Results WHERE ATM_Trx_Amount > 0 AND Account_Receiver IN ($Filter_Receiver)\r\nAND Account_Sender IN ($Filter_Sender) ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Details of ATM Transaction",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, Account_Sender, ATM_Trx_ID, ATM_Trx_Datetime, ATM_Trx_Amount FROM Grafana.UC04_Results WHERE ATM_Trx_Amount > 0 AND  Account_Receiver IN ($Filter_Receiver) \r\nAND Account_Sender IN ($Filter_Sender)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "<div style=\"border: 3px solid #66B2FF; text-align:center; border-radius:10px; margin-top:30px\">\n<h3 style=\"margin-top:10px; font-family:sans-serif; color:white; font-weight:bold\">Mobile Channel</h1>\n</div>"
   }
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 8, "w": 3, "x": 0, "y": 41 }, "format": "short", "valueName": "current" },
  {
   "title": "Average Mobile Transaction Amount over Time",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 41 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Mobile_Trx_Datetime, Mobile_Trx_Amount FROM Grafana.UC04_Results WHERE Mobile_Trx_Amount > 0 AND Account_Receiver IN ($Filter_Receiver)\r\nAND Account_Sender IN ($Filter_Sender) ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Details of Mobile Transaction",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 41 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, Account_Sender, Mobile_Trx_ID, Mobile_Trx_Datetime, Mobile_Trx_Amount FROM Grafana.UC04_Results WHERE Mobile_Trx_Amount > 0 AND Account_Receiver IN ($Filter_Receiver) \r\nAND Account_Sender IN ($Filter_Sender)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "<div style=\"border: 3px solid #FDDD60; text-align:center; border-radius:10px; margin-top:30px\">\n<h3 style=\"margin-top:10px; font-family:sans-serif; color:white; font-weight:bold\">Netbanking Channel</h1>\n</div>"
   }
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 9, "w": 3, "x": 0, "y": 52 }, "format": "short", "valueName": "current" },
  {
   "title": "Average Netbanking Transaction Amount over Time",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 52 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT IBank_Trx_Datetime, IBank_Trx_Amount FROM Grafana.UC04_Results WHERE IBank_Trx_Amount > 0 AND Account_Receiver IN ($Filter_Receiver) \r\nAND Account_Sender IN ($Filter_Sender) ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Details of Netbanking Transaction",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 52 },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT Account_Receiver, Account_Sender, IBank_Trx_ID, IBank_Trx_Datetime, IBank_Trx_Amount FROM Grafana.UC04_Results WHERE IBank_Trx_Amount > 0 AND  Account_Receiver IN ($Filter_Receiver) \r\nAND Account_Sender IN ($Filter_Sender)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}