{
 "title": "UC06a_Main",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "id",
    "query": "select  Account_Credit_Card_ID from Grafana.UC6a"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=http://172.16.11.222:3000/d/wQfTFahVz/main-dashboard?orgId=1&from=1673575007675&to=1673596607675\">\n<img src=\"https://raw.githubusercontent.com/tania21ciu/Web_Image/main/back.png\" style=\"width:60px;height:60px;\">\n</a>"
   }
  },
  {
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 4, "w": 2, "x": 1, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT * FROM uc04_data.results LIMIT 50 ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 0 },
   "options": {
    "content": "<h3 style=\"font-weight: bold; font-family: sans-serif;\">EDC Fraud Detection</h3>\n<hr style=\"height:2px;border-width:0;color:gray;background-color:gray\">\n<h4 style=\"font-weight: bold; font-family: sans-serif;\">Objectives:</h4>\n<h6 style=\"font-family: sans-serif; text-align: justify\">Deteksi transaksi melualui EDC dalam 1 hari lebih dari 100 Juta Rupiah</h6>"
   }
  },
  {
   "title": "Top 5 Account  with The Highest Total Transaction Amount",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 1, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT Account_Credit_Card_ID, EDC_Name,  Amount as Total_Transaction_Amount FROM Grafana.UC6a\r\nGROUP BY Amount DESC\r\nLIMIT 5\r\n; "
    }
   ]
  },
  {
   "title": "Top 3 Account with Detail EDC",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\r\nSELECT DISTINCT Account_Credit_Card_ID, EDC_Name, EDC_City, Amount FROM Grafana.UC6a\r\nGROUP BY Amount DESC\r\nLIMIT 3\r\n; "
    }
   ]
  },
  {
   "title": "Total Suspected Account",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT COUNT(DISTINCT Account_Credit_Card_ID) FROM Grafana.UC6a ;",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "DETAIL EDC",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT Account_Credit_Card_ID, Amount, Credit_Card_Trx_Datetime, EDC_Name, EDC_City, EDC_Address FROM Grafana.UC6a\r\nWHERE Account_Credit_Card_ID IN ($id)\r\nGROUP BY Account_Credit_Card_ID DESC\r\n\r\n;"
    }
   ]
  },
  {
   "title": "Total Anomaly Transaction Frequency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT Credit_Card_Trx_ID) FROM Grafana.UC6a ;"
    }
   ]
  },
  {
   "title": "DETAIL TRANSAKSI",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT(Credit_Card_Trx_ID), Account_Credit_Card_ID,  Credit_Card_Trx_Type, Credit_Card_Trx_Amount, Credit_Card_Trx_Datetime FROM Grafana.UC6a\r\nWHERE Account_Credit_Card_ID IN ($id)\r\nGROUP BY Credit_Card_Trx_ID DESC\r\n;"
    }
   ]
  },
  {
   "title": "Total Transaction Amount",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(Credit_Card_Trx_Amount) FROM Grafana.UC6a ;"
    }
   ]
  },
  {
   "title": "DETAIL USER",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT Account_Credit_Card_ID, User_Name, User_Address, User_Gender, User_BirthDate, User_KTP_ID FROM Grafana.UC6a\r\nWHERE Account_Credit_Card_ID IN ($id)\r\nORDER BY Account_Credit_Card_ID DESC;\r\n;"
    }
   ]
  }
 ]
}