{
 "title": "UC09_Multichannel_Fraud3_Main",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "Account",
    "query": "SELECT DISTINCT Rekening_ID from Grafana.UC9"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=http://172.16.11.222:3000/d/wQfTFahVz/main-dashboard?orgId=1&from=1673575007675&to=1673596607675\">\n<img src=\"https://raw.githubusercontent.com/tania21ciu/Web_Image/main/back.png\" style=\"width:60px;height:60px;\">\n</a>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 1, "y": 0 },
   "options": {
    "content": "<img src=\"https://raw.githubusercontent.com/maulanaakbardj/TechTitansQ/main/icon/fraud.png\"/>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 0 },
   "options": {
    "content": "<h3 style=\"font-weight: bold; font-family: sans-serif;\">Use Case 9 : Multi-channel Fraud Detection 3</h3>\n<hr style=\"height:2px;border-width:0;color:gray;background-color:gray\">\n<h4 style=\"font-weight: bold; font-family: sans-serif;\">Objectives:</h4>\n<h6 style=\"font-family: sans-serif; text-align: justify\">Mendeteksi transaksi transfer munggunakan 3 channel (ATM, BSI Mobile & BSI Netbanking) dengan Rekening Akun yang sama dengan kondisi pada lokasi yang berbeda dengan jarak ≥ 80km dalam jangka waktu 30 menit.\n</h6>"
   }
  },
  {
   "title": "Total Suspect Rekening ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT COUNT(DISTINCT(Rekening_ID)) AS \"Account\" from Grafana.UC9 WHERE Rekening_ID IN ($id)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Anomaly Transaction ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT COUNT(ATM_Trx_Amount), COUNT(Mobile_App_Trx_Amount), COUNT(Ibank_Trx_Amount) FROM Grafana.UC9 WHERE Rekening_ID IN ($id)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Anomaly Transaction Amount (Rp)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "uc04_data",
     "rawSql": "SELECT SUM(ATM_Trx_Amount), SUM(Ibank_Trx_Amount), SUM(Mobile_App_Trx_Amount) FROM Grafana.UC9 WHERE Rekening_ID IN ($id)",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Transaction Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT Rekening_ID AS \"Rekening ID\", ATM_Trx_Date AS \"ATM Date\", Mobile_App_Trx_Date AS \"Mobile Date\", Ibank_Trx_Date AS \"Netbanking Date\", Total_Transaksi AS \"Total Transaksi\" FROM Grafana.UC9 WHERE Rekening_ID IN ($id) ORDER BY ATM_Trx_Date ASC"
    }
   ]
  },
  { "title": "Waktu Indonesia Barat", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 } },
  { "title": "Waktu Indonesia Barat", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 } },
  { "title": "Waktu Indonesia Timur", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 } },
  {
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT Rekening_ID, ATM_Latitude, ATM_Longitude, ATM_City AS \"ATM City\" FROM Grafana.UC9 WHERE Rekening_ID IN ($id)"
    },
    {
     "rawSql": "SELECT DISTINCT Rekening_ID, Mobile_App_Latitude, Mobile_App_Longitude, Mobile_App_City AS \"BSI Mobile City\" FROM Grafana.UC9 WHERE Rekening_ID IN ($id)"
    },
    {
     "rawSql": "SELECT DISTINCT Rekening_ID, Ibank_Latitude, Ibank_Longitude, Ibank_Area_Location AS \"BSI Netbanking City\" FROM Grafana.UC9 WHERE Rekening_ID IN ($id)"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT Rekening_ID AS \"Rekening ID\", ATM_Trx_Amount AS \"ATM Amount\", Mobile_App_Trx_Amount AS \"Mobile Amount\", Ibank_Trx_Amount  AS \"Netbanking Amount\", Total_Transaksi AS \"Total Transaksi\" FROM Grafana.UC9 WHERE Rekening_ID IN ($id) ORDER BY ATM_Trx_Date ASC"
    }
   ]
  },
  {
   "title": "Customer Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT Rekening_ID AS \"Rekening ID\", Customer_ID AS \"Customer ID\", User_Name AS \"Name\", User_Gender AS \"Gender\", User_Address AS \"Email\", User_BirthDate AS Birtdate FROM Grafana.UC9 WHERE Rekening_ID IN ($id) ORDER BY ATM_Trx_Date ASC"
    }
   ]
  },
  {
   "title": "Fraud Area Locations",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT Rekening_ID AS \"Rekening ID\", ATM_Area_Location AS \"ATM Location\", Mobile_App_Area_Location AS \"BSI Mobile Location\", Ibank_Area_Location AS \"BSI Netbanking Location\" FROM Grafana.UC9 WHERE Rekening_ID IN ($id)"
    }
   ]
  }
 ]
}